### ISSUE TITLE
How to implement 'before_server_start' listener in an async test

### ISSUE THREAD

**Issue by xiaoxiper** [sanic-org/sanic-testing#20]
```
ERROR    sanic.error:handlers.py:146 Exception occurred while handling uri: 'http://mockserver:1234/api/v3/projects/fourth-memento-308807-test2/locations/cn/agents'
Traceback (most recent call last):
  File "xx/.venv/lib/python3.8/site-packages/sanic/app.py", line 749, in handle_request
    response = await self._run_request_middleware(
  File "xx/.venv/lib/python3.8/site-packages/sanic/app.py", line 1116, in _run_request_middleware
    response = await response
  File "xx/tests/api/base.py", line 68, in load_request_ctx
    request.ctx.engine = AIOEngine(request.app.ctx.mongo_client, database=request.ctx.database_name)
AttributeError: 'types.SimpleNamespace' object has no attribute 'mongo_client'
=============================== warnings summary ===============================
tests/api/test_agent.py::test_agent_list_get
  xx/.venv/lib/python3.8/site-packages/sanic/asgi.py:22: UserWarning: You have set a listener for "before_server_start" in ASGI mode. It will be executed as early as possible, but not before the ASGI server is started.
    warnings.warn(
```
When I used async test, I encountered the above error, but there was no problem when it was sync test. 
I have a `before_server_start`  listener to add mongo motor.

**Comment by ahopkins** [comment]
Can you share your test?

**Comment by xiaoxiper** [comment]
```
@pytest.mark.asyncio
async def test_agent_list_get(app):
    resp = await app.asgi_client.get(TEST_AGENT_URL + "/agents")
    assert resp.status == 200

**Comment by ahopkins** [comment]
So, I did a stripped down version:

```python
# conftest.py
import pytest
from sanic import Blueprint, Sanic
from sanic.response import text
from sanic_testing import TestManager


@pytest.fixture
def app():
    sanic_app = Sanic("xx", register=True)
    TestManager(sanic_app)

    api = Blueprint("api")

    @api.route("/agents")
    async def agents(request):
        return text("...")

    # autodiscover(
    #     sanic_app,
    #     registers,
    #     recursive=True
    # )

    # routes
    sanic_app.blueprint(api)

    # configs
    sanic_app.config.FALLBACK_ERROR_FORMAT = "json"

    return sanic_app
```
```python
# test_something.py

import pytest


def test_agent_list_get(app):
    request, response = app.test_client.get("/agents")
    assert response.status == 200


@pytest.mark.asyncio
async def test_agent_list_get_async(app):
    request, response = await app.asgi_client.get("/agents")
    assert response.status == 200
```

```
$ pytest tests
Test session starts (platform: linux, Python 3.9.4, pytest 5.2.1, pytest-sugar 0.9.4)
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/adam/Projects/Sanic/playground/issue20
plugins: sanic-1.6.2, cov-2.11.1, sugar-0.9.4, benchmark-3.2.3
collecting ... 
 tests/test_something.py ✓✓                                                                                                                                                             100% ██████████

Results (0.04s):
       2 passed
```

**Comment by ahopkins** [comment]
This might be a bug in the client. Needs more investigation.

**Comment by SerGeRybakov** [comment]
Yes, guys. There is a problem and it's not resolved. 

@HeathLee, in my tests finally I just created a fixture with the logic same to the listener and put it before test-client fixture.

E.g. 

```
from app import app
from db import MyDBClient

@pytest.fixture(scope="session")
def listener_fixture():
    (copy-paste listener body here)
     app.ctx.db = MyDBClient()
     return app

@pytest.fixture(scope="session")
def test_client(listener_fixture):
     return TestManager(app)

@pytest.mark.asyncio()
async def test_smth(test_client):
     assert isinstance(test_client.sanic_app.ctx.db, MyDBClient)
```

But for sure it's a bit ridiculous. Anyway I failed to find any other way to make it work.
